### ISSUE TITLE
finalfit results in table with "Coefficient" instead of "OR"

### ISSUE THREAD

**Issue by maximinio** [ewenharrison/finalfit#102]
Hi everybody,
if I run the or_plot function I get a beautiful plot with odds ratios but when I run the finalfit function it results in a table with "Coefficient" instead of "OR", very differently from what is stated in the manual.
What am I doing wrong?
Thank you in advance for your help!
Luca

**Comment by riinuots** [comment]
Hi Luca,

Thanks for posting here!
Sounds like your dependent variable is numeric, rather than a factor with two levels. Which means that finalfit() is running linear regression (=coefficient), not logistic regression (=OR), or Cox regression (=HR).

Let us know if making sure your dependent variable is in the expected format does not solve your issue.

Best wishes,
Riinu

https://finalfit.org/articles/all_tables_examples.html#linear-regression

**Comment by maximinio** [comment]
Hi Riinu,
the dependent variable is indeed numeric although it is also a factor with string labels.
Should this "convince" the function to perform a logistic regression?
By the way, I noticed that by using the finalfit.glm function I can finally get the Odds ratios!
Thank you,
Luca

**Comment by riinuots** [comment]
You can double check that your variable is in the correct format using the class() function:

```
library(finalfit)

class(colon_s$mort_5yr)
#> [1] "labelled" "factor"
class(colon_s$nodes)
#> [1] "numeric"
```

The `finalfit()` function will run logistic regression on the first, and linear regression on the second.
Any other questions about this let us know!

Best wishes,
Riinu
