### ISSUE TITLE
How to remove the "No"/"0" factor row?

### ISSUE THREAD

**Issue by tylcole** [ewenharrison/finalfit#12]
Hello,

Thanks for the great package!

Is there an option remove the "0" row or the "No" row via the finalfit function? I use a lot of binary variables, and it would be nice just to show the row for the "1" or "Yes".

![image](https://user-images.githubusercontent.com/12502856/51416164-862fb180-1b35-11e9-89c6-55f58ddd9c1f.png)

For example, in the picture above, having "Female" "1" "12888 (41.3)" "972 (44.7)" "1.15 (1.05-1.25, p=0.002" "1.15 (1.05-1.25, p=0.002" all in the same row with no row with "0" or "-".

**Comment by tylcole** [comment]
As a temporary workaround, I wrote the function collapseBinary() which takes as input a finalfit output dataframe

In:
![image](https://user-images.githubusercontent.com/12502856/51417994-170a8b00-1b3e-11e9-829e-6ca2cc5efc70.png)

Out:
![image](https://user-images.githubusercontent.com/12502856/51418062-913b0f80-1b3e-11e9-8b19-2b0970b3c30b.png)

Function:
collapseBinary = function(.data) {
  emptyRows = which(.data[,2] == "0")
  .data[emptyRows, 2:6] = .data[(emptyRows + 1), 2:6]
  .data = .data[-(emptyRows + 1),]
  replaceWithBlank = which(.data[,2] == "1")
  .data[replaceWithBlank, 2] = ""
  return(.data)
}

Use:
`collapsedTable = tableToCollapse %>% collapseBinary()`

You may have to change whatever your binary labels are, like "No" and "Yes" instead of "0" and "1"

Hope it helps until there's something more general incorporated in the function!

**Comment by ewenharrison** [comment]
Hi, 
Many thanks for you interest and work on this. One of the advantages of the finalfit dataframe is that it can be edited on the fly. So rather than adding extra options to the original functions, I've added a quick helper function `ff_remove_ref` which will remove the rows for you. It should work with all flavors of regression and factor levels. 

You can install the github version of finalfit to access this. 

Example:

```
explanatory = c("age.factor", "age", "sex.factor", "nodes", "obstruct.factor", "perfor.factor")
dependent = 'mort_5yr'
colon_s %>%
	finalfit(dependent, explanatory, add_dependent_label = FALSE) %>% 
	ff_remove_ref() %>% 
	dependent_label(colon_s, dependent)
```

Altering the OR plot can be done in a similar manner. This isn't as straightfoward and some examples will be added to future vignettes. A new "factorlist" object is created only containing the levels of interest, which is then passed to `or_plot()`. 

Example:
```
colon_s %>% 
	summary_factorlist(dependent, explanatory, total_col = TRUE, fit_id=TRUE) %>% 
	ff_merge(
		glmuni(colon_s, dependent, explanatory) %>% 
			fit2df()) %>% 
	ff_remove_ref() %>% 
	select(-`OR`) -> factorlist_plot

colon_s %>% 
	or_plot(dependent, explanatory, factorlist = factorlist_plot)
```

`ff_merge()` is very flexible, and multiple columns can be added to a regression table using it. I'll pop a comment on your other post about that. Thanks again. Let me know if anything doesn't work.

**Comment by tylcole** [comment]
That's great, thank you!
