### ISSUE TITLE
Wilcoxon vs. Mann Whitney U for non-parametric data

### ISSUE THREAD

**Issue by alexflaris** [ewenharrison/finalfit#68]
Hi,

I read this in the package documentation:

p_cont_para:
Character. Continuous variable parametric test. One of either "aov" (analysis of variance) or "t.test" for Welch two sample t-test. Note continuous non-parametric test is always Kruskal Wallis (kruskal.test) which in two-group setting is equivalent to Mann-Whitney U /Wilcoxon rank sum test.

Is there a way to specifically choose Wilcoxon for paired observations (instead of Mann-Whitney U)?

Thank you.

**Comment by ewenharrison** [comment]
Thanks. 
The type of data supplied to `summary_factorlist()` is usually single case per row, thus lending itself to a formula approach, `y~x`, where `y` is a group and has, say, two levels and `x` is a continuous variable (or vice versa). 
It is therefore not typical to have this sort of dataset structured in a way that a paired analysis makes sense, say two columns `x` and `y` both of the same variable.
So no, I would just analyse paired data in the standard manner, rather than using `summary_factorlist()`.

**Comment by alexflaris** [comment]
Thank you very much for your prompt reply,

What I was looking for would be an extension to finalfit like the ```arsenal::paired()``` function (https://cran.r-project.org/web/packages/arsenal/vignettes/paired.html). Is that something that you think would make it in the finalfit package?

Thanks again.

**Comment by ewenharrison** [comment]
Ah, ok, thank you. That makes sense. 
The vignette looks nice. 
Is there anything it doesn't do that you wish it did?

**Comment by alexflaris** [comment]
I took a closer look at ```paired()```'s tutorial and it does what I need :)
Thank you for taking the time to answer!
